### ISSUE TITLE
Support for Graphire 4 CTE-440

### ISSUE THREAD

**Issue by elmimmo** [thinkyhead/TabletMagic#11]
The PrefPane version 2.0b20 reports "No tablet found".

Mac OS X 10.10.2 does recognize the tablet's input as a mouse.

**Comment by thinkyhead** [comment]
TabletMagic is pretty old-school. It only supports serial (RS232) tablets and not the later USB models. I'm not sure how well Wacom's driver works, but they claim it is supported for OS X 10.10.x.

http://cdn.wacom.com/u/productsupport/drivers/mac/consumer/pentablet_5.3.6-6.dmg

**Comment by elmimmo** [comment]
Wacom has the bad habit of naming different generations or altogether architecturally different products the same.

The Bamboo Pen CTL-460 certainly does not work with their drivers in Yosemite and, at any rate, I was hoping to be able to also use my trusty Intuos (the very first USB Intuos, GD-0912, from around year 2000 I think), which no Wacom official drivers support in Yosemite either, so "old-school" is a relative term (^_-).

Are there no plans to support USB models? Do you know of a similar unofficial project that does, considering the existence of the [Linux Wacom Project](http://linuxwacom.sourceforge.net/wiki/index.php/Main_Page)?

**Comment by thinkyhead** [comment]
@elmimmo Unfortunately this project is not aimed at USB devices, which require a Kernel Extension (KEXT). It's an old-school driver that just connects to a serial port and does all its work in user space. There may be an open source USB / tablet driver for OS X created by someone out there, and that would be a better place to start than TabletMagic. In fact almost any USB device driver would be a better place to start. USB drivers, Kernel Extensions, HID, etc., are unfortunately all outside of my expertise.
