### ISSUE TITLE
Intuos 2 USB Support

### ISSUE THREAD

**Issue by mruepp** [thinkyhead/TabletMagic#14]
Hi, is there any outlook on integrating intous 2 USB Tablets in this driver? They dropped support for USB Tablets as well...

Thanks,

Mike

http://forum.wacom.eu/viewtopic.php?f=2&t=20494&start=10

**Comment by thinkyhead** [comment]
USB support would require a kernel extension, which is unfortunately beyond my knowledge and abilities.
